- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist
  become: yes

- name: Install basic utilities
  apt:
    name: 
      - curl
      - vim
      - htop
    state: present
  become: yes

- name: Install and configure fail2ban
  apt:
    name: fail2ban
    state: present
  become: yes

- name: Enable and start fail2ban service
  service:
    name: fail2ban
    state: started
    enabled: yes
  become: yes
